version: '3.8'

services:
  airflow:
    image: apache/airflow:2.7.1
    ports:
      - 8080:8080
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=True
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

  scheduler:
    image: apache/airflow:2.7.1
    depends_on:
      - airflow
    command: scheduler
